apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          livenessProbe:
            httpGet:
              port: 9003
              path: /actuator/health/liveness
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 9003
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 15
          ports:
            - containerPort: 9003
          volumeMounts:
            - mountPath: /workspace/config
              name: dispatcher-config-volume
      volumes:
        - name: dispatcher-config-volume
          configMap:
            name: dispatcher-config
